version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  luck-number:
    container_name: luck-number
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    restart: "on-failure"
  prometheus:
    container_name: luck-number-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: 'always'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    container_name: luck-number-grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    restart: 'always'
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    #    volumes:
    #  - /:/host:ro,rslave